POKEMON_DB = {
    "カイリュー": {
        "name": "カイリュー",
        "type1": "ドラゴン",
        "type2": "ひこう",
        "abilities": ["マルチスケイル", "せいしんりょく(隠れ)"],
        "stats": {"H": 91, "A": 134, "B": 95, "C": 100, "D": 100, "S": 80},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["いのちのたま", "じゃくてんほけん"],
        "moves": {
            "physical": ["しんそく", "じしん", "げきりん"],
            "special": [],
            "status": ["りゅうのまい", "はねやすめ"],
        },
        "tera_types": ["ノーマル", "ひこう", "はがね"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["受け崩し", "終盤全抜き"],
        "is_core": True,
        "future_tags": ["メガシンカ候補"],
    },
    "ミミッキュ": {
        "name": "ミミッキュ",
        "type1": "ゴースト",
        "type2": "フェアリー",
        "abilities": ["ばけのかわ"],
        "stats": {"H": 55, "A": 90, "B": 80, "C": 50, "D": 105, "S": 96},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["いのちのたま", "ラムのみ"],
        "moves": {
            "physical": ["シャドークロー", "じゃれつく", "かげうち"],
            "special": [],
            "status": ["つるぎのまい"],
        },
        "tera_types": ["ゴースト", "フェアリー"],
        "role_labels": ["ストッパー", "スイーパー"],
        "meta_tags": ["対ドラゴン", "切り返し"],
        "is_core": False,
        "future_tags": [],
    },
    "サーフゴー": {
        "name": "サーフゴー",
        "type1": "ゴースト",
        "type2": "はがね",
        "abilities": ["おうごんのからだ"],
        "stats": {"H": 87, "A": 60, "B": 95, "C": 133, "D": 91, "S": 84},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["たべのこし", "こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["ゴールドラッシュ", "シャドーボール", "きあいだま"],
            "status": ["わるだくみ", "トリック"],
        },
        "tera_types": ["ゴースト", "はがね"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["対受け", "サイクル"],
        "is_core": True,
        "future_tags": [],
    },
    "ガブリアス": {
        "name": "ガブリアス",
        "type1": "ドラゴン",
        "type2": "じめん",
        "abilities": ["さめはだ", "すながくれ(隠れ)"],
        "stats": {"H": 108, "A": 130, "B": 95, "C": 80, "D": 85, "S": 102},
        "recommended_nature": "ようき",
        "recommended_items": ["たべのこし", "こだわりスカーフ"],
        "moves": {
            "physical": ["じしん", "げきりん", "ストーンエッジ"],
            "special": [],
            "status": ["つるぎのまい", "ステルスロック"],
        },
        "tera_types": ["じめん", "ほのお"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["電気無効", "崩し"],
        "is_core": True,
        "future_tags": ["メガシンカ候補"],
    },
    "ロトム(ウォッシュ)": {
        "name": "ロトム(ウォッシュ)",
        "type1": "でんき",
        "type2": "みず",
        "abilities": ["ふゆう"],
        "stats": {"H": 50, "A": 65, "B": 107, "C": 105, "D": 107, "S": 86},
        "recommended_nature": "ずぶとい",
        "recommended_items": ["ゴツゴツメット", "たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ボルトチェンジ", "ハイドロポンプ"],
            "status": ["おにび", "トリック"],
        },
        "tera_types": ["みず", "でんき"],
        "role_labels": ["クッション", "サイクル"],
        "meta_tags": ["物理受け", "対地面"],
        "is_core": False,
        "future_tags": [],
    },
    "ウーラオス(れんげき)": {
        "name": "ウーラオス(れんげき)",
        "type1": "かくとう",
        "type2": "みず",
        "abilities": ["ふかしのこぶし"],
        "stats": {"H": 100, "A": 130, "B": 100, "C": 63, "D": 60, "S": 97},
        "recommended_nature": "ようき",
        "recommended_items": ["こだわりハチマキ", "いのちのたま"],
        "moves": {
            "physical": ["すいりゅうれんだ", "インファイト", "アクアジェット", "とんぼがえり"],
            "special": [],
            "status": [],
        },
        "tera_types": ["みず", "かくとう"],
        "role_labels": ["エース", "ブレイカー"],
        "meta_tags": ["壁破壊", "対受け"],
        "is_core": True,
        "future_tags": [],
    },
    "テツノドクガ": {
        "name": "テツノドクガ",
        "type1": "ほのお",
        "type2": "どく",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 80, "A": 70, "B": 60, "C": 140, "D": 110, "S": 110},
        "recommended_nature": "おくびょう",
        "recommended_items": ["ブーストエナジー", "たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ほのおのまい", "ヘドロばくだん", "エナジーボール"],
            "status": ["ちょうのまい"],
        },
        "tera_types": ["ほのお", "くさ"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["対フェアリー", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
    "ハバタクカミ": {
        "name": "ハバタクカミ",
        "type1": "ゴースト",
        "type2": "フェアリー",
        "abilities": ["こだいかっせい"],
        "stats": {"H": 55, "A": 55, "B": 55, "C": 135, "D": 135, "S": 135},
        "recommended_nature": "おくびょう",
        "recommended_items": ["ブーストエナジー", "こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["ムーンフォース", "シャドーボール"],
            "status": ["みがわり", "たたりめ"],
        },
        "tera_types": ["フェアリー", "ゴースト"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対ドラゴン"],
        "is_core": True,
        "future_tags": [],
    },
    "ディンルー": {
        "name": "ディンルー",
        "type1": "あく",
        "type2": "じめん",
        "abilities": ["わざわいのうつわ"],
        "stats": {"H": 155, "A": 110, "B": 125, "C": 55, "D": 80, "S": 45},
        "recommended_nature": "わんぱく",
        "recommended_items": ["たべのこし", "オボンのみ"],
        "moves": {
            "physical": ["じしん"],
            "special": ["あくのはどう"],
            "status": ["ステルスロック", "ふきとばし"],
        },
        "tera_types": ["あく", "じめん"],
        "role_labels": ["クッション", "受け", "起点作成"],
        "meta_tags": ["受け", "ステロ"],
        "is_core": True,
        "future_tags": [],
    },
    "ヘイラッシャ": {
        "name": "ヘイラッシャ",
        "type1": "みず",
        "type2": None,
        "abilities": ["てんねん"],
        "stats": {"H": 150, "A": 100, "B": 115, "C": 65, "D": 65, "S": 35},
        "recommended_nature": "わんぱく",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": ["ウェーブタックル"],
            "special": [],
            "status": ["ねむる", "あくび"],
        },
        "tera_types": ["みず"],
        "role_labels": ["クッション", "受け"],
        "meta_tags": ["物理受け", "積み対策"],
        "is_core": False,
        "future_tags": [],
    },
    "キョジオーン": {
        "name": "キョジオーン",
        "type1": "いわ",
        "type2": None,
        "abilities": ["きよめのしお"],
        "stats": {"H": 100, "A": 100, "B": 130, "C": 45, "D": 90, "S": 35},
        "recommended_nature": "わんぱく",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": [],
            "status": ["しおづけ", "じこさいせい", "まもる", "ステルスロック"],
        },
        "tera_types": ["いわ", "はがね"],
        "role_labels": ["クッション", "受け", "起点作成"],
        "meta_tags": ["受け", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
    "サザンドラ": {
        "name": "サザンドラ",
        "type1": "あく",
        "type2": "ドラゴン",
        "abilities": ["ふゆう"],
        "stats": {"H": 92, "A": 105, "B": 90, "C": 125, "D": 90, "S": 98},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりメガネ", "とつげきチョッキ"],
        "moves": {
            "physical": ["とんぼがえり"],
            "special": ["あくのはどう", "りゅうせいぐん", "ラスターカノン"],
            "status": [],
        },
        "tera_types": ["はがね", "ドラゴン"],
        "role_labels": ["エース"],
        "meta_tags": ["崩し", "対エスパー"],
        "is_core": False,
        "future_tags": [],
    },
    "カバルドン": {
        "name": "カバルドン",
        "type1": "じめん",
        "type2": None,
        "abilities": ["すなおこし", "すなちから(隠れ)"],
        "stats": {"H": 108, "A": 112, "B": 118, "C": 68, "D": 72, "S": 47},
        "recommended_nature": "わんぱく",
        "recommended_items": ["たべのこし", "ゴツゴツメット"],
        "moves": {
            "physical": ["じしん"],
            "special": [],
            "status": ["あくび", "ステルスロック", "なまける"],
        },
        "tera_types": ["じめん", "みず"],
        "role_labels": ["クッション", "受け", "起点作成"],
        "meta_tags": ["ステロ", "物理受け"],
        "is_core": True,
        "future_tags": [],
    },
    "ブリムオン": {
        "name": "ブリムオン",
        "type1": "エスパー",
        "type2": "フェアリー",
        "abilities": ["マジックミラー"],
        "stats": {"H": 57, "A": 90, "B": 95, "C": 136, "D": 103, "S": 29},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["きあいのタスキ", "いのちのたま"],
        "moves": {
            "physical": [],
            "special": ["マジカルシャイン", "サイコキネシス"],
            "status": ["トリックルーム", "いやしのねがい"],
        },
        "tera_types": ["フェアリー", "エスパー"],
        "role_labels": ["トリックルーム", "エース"],
        "meta_tags": ["対ドラゴン", "起点回避"],
        "is_core": False,
        "future_tags": [],
    },
    "トドロクツキ": {
        "name": "トドロクツキ",
        "type1": "あく",
        "type2": "ドラゴン",
        "abilities": ["こだいかっせい"],
        "stats": {"H": 105, "A": 139, "B": 71, "C": 55, "D": 101, "S": 119},
        "recommended_nature": "ようき",
        "recommended_items": ["ブーストエナジー", "いのちのたま"],
        "moves": {
            "physical": ["はたきおとす", "アクロバット", "じしん"],
            "special": [],
            "status": ["りゅうのまい"],
        },
        "tera_types": ["ひこう", "あく"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速崩し", "終盤全抜き"],
        "is_core": True,
        "future_tags": [],
    },
    "パオジアン": {
        "name": "パオジアン",
        "type1": "あく",
        "type2": "こおり",
        "abilities": ["わざわいのつるぎ"],
        "stats": {"H": 80, "A": 120, "B": 80, "C": 90, "D": 65, "S": 135},
        "recommended_nature": "ようき",
        "recommended_items": ["いのちのたま", "きあいのタスキ"],
        "moves": {
            "physical": ["つららおとし", "かみくだく", "せいなるつるぎ"],
            "special": [],
            "status": ["つるぎのまい"],
        },
        "tera_types": ["あく", "こおり"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対ドラゴン"],
        "is_core": True,
        "future_tags": [],
    },
    "ウルガモス": {
        "name": "ウルガモス",
        "type1": "ほのお",
        "type2": "むし",
        "abilities": ["ほのおのからだ", "むしのしらせ(隠れ)"],
        "stats": {"H": 85, "A": 60, "B": 65, "C": 135, "D": 105, "S": 100},
        "recommended_nature": "おくびょう",
        "recommended_items": ["たべのこし", "ラムのみ"],
        "moves": {
            "physical": [],
            "special": ["ほのおのまい", "むしのさざめき", "ギガドレイン"],
            "status": ["ちょうのまい"],
        },
        "tera_types": ["くさ", "ほのお"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["特殊アタッカー", "対草"],
        "is_core": False,
        "future_tags": [],
    },
    "モロバレル": {
        "name": "モロバレル",
        "type1": "くさ",
        "type2": "どく",
        "abilities": ["さいせいりょく", "ぼうじん(隠れ)"],
        "stats": {"H": 114, "A": 85, "B": 70, "C": 85, "D": 80, "S": 30},
        "recommended_nature": "おだやか",
        "recommended_items": ["くろいヘドロ", "ゴツゴツメット"],
        "moves": {
            "physical": [],
            "special": ["ギガドレイン"],
            "status": ["キノコのほうし", "クリアスモッグ", "いかりのこな"],
        },
        "tera_types": ["くさ", "みず"],
        "role_labels": ["クッション", "サポート"],
        "meta_tags": ["状態異常", "対水"],
        "is_core": False,
        "future_tags": [],
    },
    "アーマーガア": {
        "name": "アーマーガア",
        "type1": "ひこう",
        "type2": "はがね",
        "abilities": ["ミラーアーマー", "プレッシャー(隠れ)"],
        "stats": {"H": 98, "A": 87, "B": 105, "C": 53, "D": 85, "S": 67},
        "recommended_nature": "わんぱく",
        "recommended_items": ["ゴツゴツメット", "たべのこし"],
        "moves": {
            "physical": ["ボディプレス", "とんぼがえり"],
            "special": [],
            "status": ["てっぺき", "はねやすめ"],
        },
        "tera_types": ["はがね", "ひこう"],
        "role_labels": ["クッション", "受け"],
        "meta_tags": ["物理受け", "対地面"],
        "is_core": False,
        "future_tags": [],
    },
    "カイオーガ": {
        "name": "カイオーガ",
        "type1": "みず",
        "type2": None,
        "abilities": ["あめふらし"],
        "stats": {"H": 100, "A": 100, "B": 90, "C": 150, "D": 140, "S": 90},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["こだわりメガネ", "しずくプレート"],
        "moves": {
            "physical": [],
            "special": ["しおふき", "こんげんのはどう", "かみなり", "れいとうビーム"],
            "status": [],
        },
        "tera_types": ["みず", "でんき"],
        "role_labels": ["エース"],
        "meta_tags": ["特殊アタッカー", "対鋼"],
        "is_core": True,
        "future_tags": [],
    },
    "ザシアン": {
        "name": "ザシアン",
        "type1": "フェアリー",
        "type2": "はがね",
        "abilities": ["ふとうのけん"],
        "stats": {"H": 92, "A": 170, "B": 115, "C": 80, "D": 115, "S": 148},
        "recommended_nature": "ようき",
        "recommended_items": ["くちたけん"],
        "moves": {
            "physical": ["きょじゅうざん", "じゃれつく", "インファイト"],
            "special": [],
            "status": ["つるぎのまい"],
        },
        "tera_types": ["フェアリー", "はがね"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対ドラゴン"],
        "is_core": True,
        "future_tags": [],
    },
    "テツノカイナ": {
        "name": "テツノカイナ",
        "type1": "かくとう",
        "type2": "でんき",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 154, "A": 140, "B": 108, "C": 50, "D": 68, "S": 50},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["ブーストエナジー", "たべのこし"],
        "moves": {
            "physical": ["ドレインパンチ", "ワイルドボルト", "つるぎのまい"],
            "special": [],
            "status": ["はらだいこ"],
        },
        "tera_types": ["でんき", "かくとう"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["対水", "物理アタッカー"],
        "is_core": False,
        "future_tags": [],
    },
    "テツノツツミ": {
        "name": "テツノツツミ",
        "type1": "こおり",
        "type2": "みず",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 56, "A": 80, "B": 65, "C": 124, "D": 60, "S": 136},
        "recommended_nature": "おくびょう",
        "recommended_items": ["ブーストエナジー", "こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["ハイドロポンプ", "れいとうビーム", "フリーズドライ"],
            "status": ["クイックターン"],
        },
        "tera_types": ["こおり", "みず"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対飛行"],
        "is_core": True,
        "future_tags": [],
    },
    "ドラパルト": {
        "name": "ドラパルト",
        "type1": "ドラゴン",
        "type2": "ゴースト",
        "abilities": ["すりぬけ", "のろわれボディ(隠れ)"],
        "stats": {"H": 88, "A": 120, "B": 75, "C": 100, "D": 75, "S": 142},
        "recommended_nature": "ようき",
        "recommended_items": ["こだわりハチマキ", "いのちのたま"],
        "moves": {
            "physical": ["ドラゴンアロー", "ゴーストダイブ", "とんぼがえり"],
            "special": [],
            "status": ["りゅうのまい"],
        },
        "tera_types": ["ゴースト", "ドラゴン"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "切り返し"],
        "is_core": True,
        "future_tags": [],
    },
    "サンダー": {
        "name": "サンダー",
        "type1": "でんき",
        "type2": "ひこう",
        "abilities": ["せいでんき", "プレッシャー(隠れ)"],
        "stats": {"H": 90, "A": 90, "B": 85, "C": 125, "D": 90, "S": 100},
        "recommended_nature": "おくびょう",
        "recommended_items": ["ブーツ", "たべのこし"],
        "moves": {
            "physical": [],
            "special": ["10まんボルト", "ぼうふう", "ねっぷう"],
            "status": ["はねやすめ"],
        },
        "tera_types": ["でんき", "ひこう"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["対草", "対鋼"],
        "is_core": False,
        "future_tags": [],
    },
    "ハッサム": {
        "name": "ハッサム",
        "type1": "むし",
        "type2": "はがね",
        "abilities": ["テクニシャン", "ライトメタル(隠れ)"],
        "stats": {"H": 70, "A": 130, "B": 100, "C": 55, "D": 80, "S": 65},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["たべのこし", "こだわりハチマキ"],
        "moves": {
            "physical": ["バレットパンチ", "とんぼがえり"],
            "special": [],
            "status": ["つるぎのまい", "はねやすめ"],
        },
        "tera_types": ["はがね", "ひこう"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["対フェアリー", "物理アタッカー"],
        "is_core": False,
        "future_tags": ["メガシンカ候補"],
    },
    "ドドゲザン": {
        "name": "ドドゲザン",
        "type1": "あく",
        "type2": "はがね",
        "abilities": ["そうだいしょう", "まけんき(隠れ)"],
        "stats": {"H": 100, "A": 135, "B": 120, "C": 60, "D": 85, "S": 50},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["くろいメガネ", "たべのこし"],
        "moves": {
            "physical": ["ドゲザン", "アイアンヘッド", "ふいうち"],
            "special": [],
            "status": ["ちょうはつ"],
        },
        "tera_types": ["あく", "はがね"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["対ゴースト", "切り返し"],
        "is_core": True,
        "future_tags": [],
    },
    "ブースター": {
        "name": "ブースター",
        "type1": "ほのお",
        "type2": None,
        "abilities": ["こんじょう", "もらいび(隠れ)"],
        "stats": {"H": 65, "A": 130, "B": 60, "C": 95, "D": 110, "S": 65},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["かえんだま"],
        "moves": {
            "physical": ["フレアドライブ", "ばかぢから", "でんこうせっか"],
            "special": [],
            "status": ["ねがいごと"],
        },
        "tera_types": ["ほのお", "ノーマル"],
        "role_labels": ["ブレイカー"],
        "meta_tags": ["受け崩し", "対鋼"],
        "is_core": False,
        "future_tags": [],
    },
    "トリトドン": {
        "name": "トリトドン",
        "type1": "みず",
        "type2": "じめん",
        "abilities": ["よびみず", "ねんちゃく(隠れ)"],
        "stats": {"H": 111, "A": 83, "B": 68, "C": 92, "D": 82, "S": 39},
        "recommended_nature": "おだやか",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ねっとう", "だいちのちから"],
            "status": ["じこさいせい", "あくび"],
        },
        "tera_types": ["みず", "じめん"],
        "role_labels": ["クッション", "受け"],
        "meta_tags": ["対電気", "対水"],
        "is_core": False,
        "future_tags": [],
    },
    "サーフゴー(スカーフ)": {
        "name": "サーフゴー(スカーフ)",
        "type1": "ゴースト",
        "type2": "はがね",
        "abilities": ["おうごんのからだ"],
        "stats": {"H": 87, "A": 60, "B": 95, "C": 133, "D": 91, "S": 84},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりスカーフ"],
        "moves": {
            "physical": [],
            "special": ["ゴールドラッシュ", "シャドーボール", "きあいだま"],
            "status": ["トリック"],
        },
        "tera_types": ["ゴースト", "はがね"],
        "role_labels": ["スイーパー", "ストッパー"],
        "meta_tags": ["高速化", "切り返し"],
        "is_core": False,
        "future_tags": [],
    },
    "ラッシャ(ヘイラッシャ)": {
        "name": "ラッシャ(ヘイラッシャ)",
        "type1": "みず",
        "type2": None,
        "abilities": ["てんねん"],
        "stats": {"H": 150, "A": 100, "B": 115, "C": 65, "D": 65, "S": 35},
        "recommended_nature": "わんぱく",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": ["ウェーブタックル"],
            "special": [],
            "status": ["あくび", "ねむる"],
        },
        "tera_types": ["みず"],
        "role_labels": ["クッション"],
        "meta_tags": ["物理受け"],
        "is_core": False,
        "future_tags": [],
    },
    "イーユイ": {
        "name": "イーユイ",
        "type1": "ほのお",
        "type2": "あく",
        "abilities": ["わざわいのたま"],
        "stats": {"H": 55, "A": 80, "B": 80, "C": 135, "D": 120, "S": 100},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりメガネ", "とつげきチョッキ"],
        "moves": {
            "physical": [],
            "special": ["かえんほうしゃ", "オーバーヒート", "あくのはどう"],
            "status": ["テラバースト"],
        },
        "tera_types": ["ほのお", "あく"],
        "role_labels": ["エース", "ブレイカー"],
        "meta_tags": ["崩し", "対はがね"],
        "is_core": True,
        "future_tags": [],
    },
    "イダイナキバ": {
        "name": "イダイナキバ",
        "type1": "じめん",
        "type2": "かくとう",
        "abilities": ["こだいかっせい"],
        "stats": {"H": 115, "A": 131, "B": 131, "C": 53, "D": 53, "S": 87},
        "recommended_nature": "わんぱく",
        "recommended_items": ["ブーストエナジー", "ゴツゴツメット"],
        "moves": {
            "physical": ["じしん", "インファイト", "こうそくスピン"],
            "special": [],
            "status": ["ステルスロック"],
        },
        "tera_types": ["じめん", "かくとう"],
        "role_labels": ["クッション", "起点作成"],
        "meta_tags": ["ステロ", "対でんき"],
        "is_core": False,
        "future_tags": [],
    },
    "テツノワダチ": {
        "name": "テツノワダチ",
        "type1": "じめん",
        "type2": "はがね",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 90, "A": 112, "B": 120, "C": 72, "D": 70, "S": 106},
        "recommended_nature": "ようき",
        "recommended_items": ["ブーストエナジー"],
        "moves": {
            "physical": ["じしん", "アイアンヘッド", "こうそくスピン"],
            "special": [],
            "status": ["ステルスロック"],
        },
        "tera_types": ["じめん", "はがね"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["ステロ", "対フェアリー"],
        "is_core": False,
        "future_tags": [],
    },
    "テツノブジン": {
        "name": "テツノブジン",
        "type1": "フェアリー",
        "type2": "かくとう",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 74, "A": 130, "B": 90, "C": 120, "D": 60, "S": 116},
        "recommended_nature": "ようき",
        "recommended_items": ["ブーストエナジー", "きあいのタスキ"],
        "moves": {
            "physical": ["インファイト", "シャドークロー"],
            "special": ["ムーンフォース"],
            "status": ["つるぎのまい"],
        },
        "tera_types": ["フェアリー", "かくとう"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対ドラゴン"],
        "is_core": True,
        "future_tags": [],
    },
    "セグレイブ": {
        "name": "セグレイブ",
        "type1": "ドラゴン",
        "type2": "こおり",
        "abilities": ["ねつこうかん"],
        "stats": {"H": 115, "A": 145, "B": 92, "C": 75, "D": 86, "S": 87},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["たべのこし", "いのちのたま"],
        "moves": {
            "physical": ["つららばり", "げきりん", "じしん"],
            "special": [],
            "status": ["りゅうのまい"],
        },
        "tera_types": ["こおり", "ドラゴン"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["崩し", "対ドラゴン"],
        "is_core": True,
        "future_tags": [],
    },
    "マスカーニャ": {
        "name": "マスカーニャ",
        "type1": "くさ",
        "type2": "あく",
        "abilities": ["へんげんじざい", "しんりょく(隠れ)"],
        "stats": {"H": 76, "A": 110, "B": 70, "C": 81, "D": 70, "S": 123},
        "recommended_nature": "ようき",
        "recommended_items": ["きあいのタスキ", "いのちのたま"],
        "moves": {
            "physical": ["トリックフラワー", "はたきおとす", "とんぼがえり"],
            "special": [],
            "status": ["かげうち"],
        },
        "tera_types": ["くさ", "あく"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対水"],
        "is_core": True,
        "future_tags": [],
    },
    "ウルガモス(テラス草)": {
        "name": "ウルガモス(テラス草)",
        "type1": "ほのお",
        "type2": "むし",
        "abilities": ["ほのおのからだ"],
        "stats": {"H": 85, "A": 60, "B": 65, "C": 135, "D": 105, "S": 100},
        "recommended_nature": "おくびょう",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ほのおのまい", "ギガドレイン"],
            "status": ["ちょうのまい", "みがわり"],
        },
        "tera_types": ["くさ", "ほのお"],
        "role_labels": ["スイーパー"],
        "meta_tags": ["対水", "積みエース"],
        "is_core": False,
        "future_tags": [],
    },
    "オーガポン(かまど)": {
        "name": "オーガポン(かまど)",
        "type1": "くさ",
        "type2": "ほのお",
        "abilities": ["かたやぶり"],
        "stats": {"H": 80, "A": 120, "B": 84, "C": 60, "D": 96, "S": 110},
        "recommended_nature": "ようき",
        "recommended_items": ["かまどのめん"],
        "moves": {
            "physical": ["ツタこんぼう", "ウッドホーン"],
            "special": [],
            "status": ["つるぎのまい", "ニードルガード"],
        },
        "tera_types": ["ほのお", "くさ"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["対水", "崩し"],
        "is_core": True,
        "future_tags": [],
    },
    "ガチグマ(アカツキ)": {
        "name": "ガチグマ(アカツキ)",
        "type1": "じめん",
        "type2": "ノーマル",
        "abilities": ["しんがん"],
        "stats": {"H": 113, "A": 70, "B": 120, "C": 135, "D": 65, "S": 52},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["たべのこし", "こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["ブラッドムーン", "だいちのちから"],
            "status": ["あくび", "なまける"],
        },
        "tera_types": ["ノーマル", "じめん"],
        "role_labels": ["ブレイカー", "クッション"],
        "meta_tags": ["崩し", "対でんき"],
        "is_core": True,
        "future_tags": [],
    },
    "ドドゲザン(先発)": {
        "name": "ドドゲザン(先発)",
        "type1": "あく",
        "type2": "はがね",
        "abilities": ["そうだいしょう"],
        "stats": {"H": 100, "A": 135, "B": 120, "C": 60, "D": 85, "S": 50},
        "recommended_nature": "わんぱく",
        "recommended_items": ["きあいのタスキ"],
        "moves": {
            "physical": ["ドゲザン", "ふいうち"],
            "special": [],
            "status": ["ステルスロック", "ちょうはつ"],
        },
        "tera_types": ["あく", "はがね"],
        "role_labels": ["起点作成", "サポート"],
        "meta_tags": ["ステロ", "対ゴースト"],
        "is_core": False,
        "future_tags": [],
    },
    "イーユイ(メガ想定)": {
        "name": "イーユイ(メガ想定)",
        "type1": "ほのお",
        "type2": "あく",
        "abilities": ["メガ想定"],
        "stats": {"H": 55, "A": 90, "B": 90, "C": 155, "D": 130, "S": 110},
        "recommended_nature": "おくびょう",
        "recommended_items": ["メガストーン想定"],
        "moves": {
            "physical": [],
            "special": ["かえんほうしゃ", "あくのはどう", "オーバーヒート"],
            "status": ["わるだくみ"],
        },
        "tera_types": ["ほのお", "あく"],
        "role_labels": ["エース"],
        "meta_tags": ["未来想定"],
        "is_core": False,
        "future_tags": ["メガシンカ候補"],
    },
    "エースバーン": {
        "name": "エースバーン",
        "type1": "ほのお",
        "type2": None,
        "abilities": ["リベロ", "もうか(隠れ)"],
        "stats": {"H": 80, "A": 116, "B": 75, "C": 65, "D": 75, "S": 119},
        "recommended_nature": "ようき",
        "recommended_items": ["いのちのたま", "きあいのタスキ"],
        "moves": {
            "physical": ["かえんボール", "とびひざげり", "ふいうち"],
            "special": [],
            "status": ["とんぼがえり"],
        },
        "tera_types": ["ほのお", "かくとう"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対くさ"],
        "is_core": False,
        "future_tags": [],
    },
    "リザードン": {
        "name": "リザードン",
        "type1": "ほのお",
        "type2": "ひこう",
        "abilities": ["もうか", "サンパワー(隠れ)"],
        "stats": {"H": 78, "A": 84, "B": 78, "C": 109, "D": 85, "S": 100},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりメガネ", "ブーツ"],
        "moves": {
            "physical": [],
            "special": ["ねっぷう", "エアスラッシュ", "ソーラービーム", "りゅうのはどう"],
            "status": [],
        },
        "tera_types": ["ほのお", "ひこう"],
        "role_labels": ["エース"],
        "meta_tags": ["対草", "対虫"],
        "is_core": False,
        "future_tags": ["メガシンカ候補"],
    },
    "バンギラス": {
        "name": "バンギラス",
        "type1": "いわ",
        "type2": "あく",
        "abilities": ["すなおこし", "きんちょうかん(隠れ)"],
        "stats": {"H": 100, "A": 134, "B": 110, "C": 95, "D": 100, "S": 61},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["たべのこし", "じゃくてんほけん"],
        "moves": {
            "physical": ["ストーンエッジ", "かみくだく"],
            "special": [],
            "status": ["ステルスロック", "りゅうのまい"],
        },
        "tera_types": ["あく", "いわ"],
        "role_labels": ["クッション", "ブレイカー", "起点作成"],
        "meta_tags": ["ステロ", "対ゴースト"],
        "is_core": False,
        "future_tags": ["メガシンカ候補"],
    },
    "キラフロル": {
        "name": "キラフロル",
        "type1": "いわ",
        "type2": "どく",
        "abilities": ["どくげしょう", "ふしょく(隠れ)"],
        "stats": {"H": 83, "A": 55, "B": 90, "C": 130, "D": 81, "S": 86},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["きあいのタスキ"],
        "moves": {
            "physical": [],
            "special": ["パワージェム", "ヘドロばくだん", "だいちのちから"],
            "status": ["ステルスロック"],
        },
        "tera_types": ["どく", "いわ"],
        "role_labels": ["サポート", "起点作成"],
        "meta_tags": ["ステロ", "対フェアリー"],
        "is_core": False,
        "future_tags": [],
    },
    "グライオン": {
        "name": "グライオン",
        "type1": "じめん",
        "type2": "ひこう",
        "abilities": ["ポイズンヒール", "すながくれ(隠れ)"],
        "stats": {"H": 75, "A": 95, "B": 125, "C": 45, "D": 75, "S": 95},
        "recommended_nature": "わんぱく",
        "recommended_items": ["どくどくだま"],
        "moves": {
            "physical": ["じしん"],
            "special": [],
            "status": ["どくどく", "まもる", "はねやすめ"],
        },
        "tera_types": ["じめん", "ひこう"],
        "role_labels": ["クッション", "サポート"],
        "meta_tags": ["対でんき", "受け"],
        "is_core": False,
        "future_tags": [],
    },
    "ラオス(いちげき)": {
        "name": "ラオス(いちげき)",
        "type1": "かくとう",
        "type2": "あく",
        "abilities": ["ふかしのこぶし"],
        "stats": {"H": 100, "A": 130, "B": 100, "C": 63, "D": 60, "S": 97},
        "recommended_nature": "ようき",
        "recommended_items": ["こだわりハチマキ"],
        "moves": {
            "physical": ["あんこくきょうだ", "インファイト", "ふいうち", "とんぼがえり"],
            "special": [],
            "status": [],
        },
        "tera_types": ["あく", "かくとう"],
        "role_labels": ["エース", "ブレイカー"],
        "meta_tags": ["対受け", "崩し"],
        "is_core": True,
        "future_tags": [],
    },
    "サケブシッポ": {
        "name": "サケブシッポ",
        "type1": "フェアリー",
        "type2": "エスパー",
        "abilities": ["こだいかっせい"],
        "stats": {"H": 115, "A": 65, "B": 99, "C": 65, "D": 115, "S": 111},
        "recommended_nature": "おだやか",
        "recommended_items": ["ひかりのねんど"],
        "moves": {
            "physical": [],
            "special": ["マジカルシャイン"],
            "status": ["リフレクター", "ひかりのかべ", "いやしのねがい"],
        },
        "tera_types": ["フェアリー", "エスパー"],
        "role_labels": ["サポート", "起点作成"],
        "meta_tags": ["壁", "起点作成"],
        "is_core": False,
        "future_tags": [],
    },
    "レジエレキ": {
        "name": "レジエレキ",
        "type1": "でんき",
        "type2": None,
        "abilities": ["トランジスタ"],
        "stats": {"H": 80, "A": 100, "B": 50, "C": 100, "D": 50, "S": 200},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["サンダープリズン", "ボルトチェンジ", "テラバースト"],
            "status": ["でんじは"],
        },
        "tera_types": ["でんき", "こおり"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["高速アタッカー", "対水"],
        "is_core": True,
        "future_tags": [],
    },
    "ランドロス(霊獣)": {
        "name": "ランドロス(霊獣)",
        "type1": "じめん",
        "type2": "ひこう",
        "abilities": ["いかく", "ちからずく(隠れ)"],
        "stats": {"H": 89, "A": 125, "B": 90, "C": 115, "D": 80, "S": 101},
        "recommended_nature": "ようき",
        "recommended_items": ["こだわりスカーフ", "ゴツゴツメット"],
        "moves": {
            "physical": ["じしん", "とんぼがえり", "がんせきふうじ"],
            "special": [],
            "status": ["ステルスロック"],
        },
        "tera_types": ["じめん", "ひこう"],
        "role_labels": ["クッション", "起点作成"],
        "meta_tags": ["ステロ", "対でんき"],
        "is_core": True,
        "future_tags": [],
    },
    "ヒードラン": {
        "name": "ヒードラン",
        "type1": "ほのお",
        "type2": "はがね",
        "abilities": ["もらいび", "ほのおのからだ(隠れ)"],
        "stats": {"H": 91, "A": 90, "B": 106, "C": 130, "D": 106, "S": 77},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["たべのこし", "こだわりメガネ"],
        "moves": {
            "physical": [],
            "special": ["マグマストーム", "ラスターカノン", "だいちのちから"],
            "status": ["ステルスロック"],
        },
        "tera_types": ["ほのお", "はがね"],
        "role_labels": ["クッション", "エース", "起点作成"],
        "meta_tags": ["対フェアリー", "ステロ"],
        "is_core": True,
        "future_tags": [],
    },
    "ゴリランダー": {
        "name": "ゴリランダー",
        "type1": "くさ",
        "type2": None,
        "abilities": ["グラスメイカー", "はりきり(隠れ)"],
        "stats": {"H": 100, "A": 125, "B": 90, "C": 60, "D": 70, "S": 85},
        "recommended_nature": "いじっぱり",
        "recommended_items": ["こだわりハチマキ", "とつげきチョッキ"],
        "moves": {
            "physical": ["グラススライダー", "ウッドハンマー", "はたきおとす", "とんぼがえり"],
            "special": [],
            "status": [],
        },
        "tera_types": ["くさ", "あく"],
        "role_labels": ["エース"],
        "meta_tags": ["対水", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
    "カイオーガ(スカーフ)": {
        "name": "カイオーガ(スカーフ)",
        "type1": "みず",
        "type2": None,
        "abilities": ["あめふらし"],
        "stats": {"H": 100, "A": 100, "B": 90, "C": 150, "D": 140, "S": 90},
        "recommended_nature": "おくびょう",
        "recommended_items": ["こだわりスカーフ"],
        "moves": {
            "physical": [],
            "special": ["しおふき", "なみのり", "かみなり", "れいとうビーム"],
            "status": [],
        },
        "tera_types": ["みず", "でんき"],
        "role_labels": ["スイーパー", "エース"],
        "meta_tags": ["高速化", "対はがね"],
        "is_core": True,
        "future_tags": [],
    },
    "テラパゴス": {
        "name": "テラパゴス",
        "type1": "ノーマル",
        "type2": None,
        "abilities": ["テラスチェンジ"],
        "stats": {"H": 90, "A": 65, "B": 85, "C": 135, "D": 105, "S": 60},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": ["テラクラスター", "だいちのちから"],
            "status": ["リフレクター", "ねむる"],
        },
        "tera_types": ["ノーマル"],
        "role_labels": ["エース", "クッション"],
        "meta_tags": ["特殊アタッカー", "対ドラゴン"],
        "is_core": True,
        "future_tags": ["テラス環境想定"],
    },
    "ウネルミナモ": {
        "name": "ウネルミナモ",
        "type1": "みず",
        "type2": "ドラゴン",
        "abilities": ["こだいかっせい"],
        "stats": {"H": 99, "A": 83, "B": 91, "C": 125, "D": 83, "S": 109},
        "recommended_nature": "おくびょう",
        "recommended_items": ["ブーストエナジー"],
        "moves": {
            "physical": [],
            "special": ["ハイドロポンプ", "りゅうせいぐん", "ねっぷう"],
            "status": ["ちょうはつ"],
        },
        "tera_types": ["みず", "ドラゴン"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["対ほのお", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
    "テツノイサハ": {
        "name": "テツノイサハ",
        "type1": "くさ",
        "type2": "エスパー",
        "abilities": ["クォークチャージ"],
        "stats": {"H": 90, "A": 130, "B": 88, "C": 70, "D": 108, "S": 104},
        "recommended_nature": "ようき",
        "recommended_items": ["ブーストエナジー"],
        "moves": {
            "physical": ["リーフブレード", "サイコカッター", "でんこうせっか"],
            "special": [],
            "status": ["つるぎのまい"],
        },
        "tera_types": ["くさ", "エスパー"],
        "role_labels": ["エース", "スイーパー"],
        "meta_tags": ["対水", "高速アタッカー"],
        "is_core": False,
        "future_tags": [],
    },
    "クエスパトラ": {
        "name": "クエスパトラ",
        "type1": "エスパー",
        "type2": None,
        "abilities": ["かそく", "びんじょう(隠れ)"],
        "stats": {"H": 95, "A": 60, "B": 60, "C": 101, "D": 60, "S": 105},
        "recommended_nature": "おくびょう",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ルミナコリジョン"],
            "status": ["みがわり", "てっぺき", "バトンタッチ"],
        },
        "tera_types": ["エスパー"],
        "role_labels": ["スイーパー"],
        "meta_tags": ["積みエース", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
    "ドオー": {
        "name": "ドオー",
        "type1": "どく",
        "type2": "じめん",
        "abilities": ["てんねん", "ちょすい(隠れ)"],
        "stats": {"H": 130, "A": 75, "B": 60, "C": 45, "D": 100, "S": 20},
        "recommended_nature": "おだやか",
        "recommended_items": ["くろいヘドロ"],
        "moves": {
            "physical": ["じしん"],
            "special": [],
            "status": ["どくどく", "じこさいせい", "あくび"],
        },
        "tera_types": ["どく", "みず"],
        "role_labels": ["クッション", "受け"],
        "meta_tags": ["積み対策", "対でんき"],
        "is_core": False,
        "future_tags": [],
    },
    "サーフゴー(サイクル)": {
        "name": "サーフゴー(サイクル)",
        "type1": "ゴースト",
        "type2": "はがね",
        "abilities": ["おうごんのからだ"],
        "stats": {"H": 87, "A": 60, "B": 95, "C": 133, "D": 91, "S": 84},
        "recommended_nature": "おくびょう",
        "recommended_items": ["たべのこし"],
        "moves": {
            "physical": [],
            "special": ["ゴールドラッシュ", "シャドーボール"],
            "status": ["ボルトチェンジ", "トリック"],
        },
        "tera_types": ["はがね", "ゴースト"],
        "role_labels": ["クッション", "サイクル"],
        "meta_tags": ["サイクル", "対受け"],
        "is_core": False,
        "future_tags": [],
    },
    "トリックルームエース(代表)": {
        "name": "トリックルームエース(代表)",
        "type1": "はがね",
        "type2": "フェアリー",
        "abilities": ["ふゆう"],
        "stats": {"H": 60, "A": 95, "B": 115, "C": 130, "D": 95, "S": 50},
        "recommended_nature": "ひかえめ",
        "recommended_items": ["いのちのたま"],
        "moves": {
            "physical": ["じしん"],
            "special": ["ラスターカノン", "サイコキネシス"],
            "status": ["トリックルーム"],
        },
        "tera_types": ["はがね", "フェアリー"],
        "role_labels": ["トリックルーム", "エース"],
        "meta_tags": ["トリル", "崩し"],
        "is_core": False,
        "future_tags": [],
    },
}
